// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVVNK_uuxTnZl9fmmxj9aFcXs-2mzLrCs',
    appId: '1:595183160017:web:58453eb41466ee706f93f0',
    messagingSenderId: '595183160017',
    projectId: 'dsm-project-7087e',
    authDomain: 'dsm-project-7087e.firebaseapp.com',
    storageBucket: 'dsm-project-7087e.firebasestorage.app',
    measurementId: 'G-KJ09SNXGY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4P0tRRkFCzIqlohCD37M8YwvVB2GaIKk',
    appId: '1:595183160017:android:f0a02d03cb76cba76f93f0',
    messagingSenderId: '595183160017',
    projectId: 'dsm-project-7087e',
    storageBucket: 'dsm-project-7087e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQYpvlbRMMhfIaJLmiZRH9Ha35VZbMr6k',
    appId: '1:595183160017:ios:92d08c0d2a12fa946f93f0',
    messagingSenderId: '595183160017',
    projectId: 'dsm-project-7087e',
    storageBucket: 'dsm-project-7087e.firebasestorage.app',
    iosBundleId: 'com.example.messageNotifier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQYpvlbRMMhfIaJLmiZRH9Ha35VZbMr6k',
    appId: '1:595183160017:ios:92d08c0d2a12fa946f93f0',
    messagingSenderId: '595183160017',
    projectId: 'dsm-project-7087e',
    storageBucket: 'dsm-project-7087e.firebasestorage.app',
    iosBundleId: 'com.example.messageNotifier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVVNK_uuxTnZl9fmmxj9aFcXs-2mzLrCs',
    appId: '1:595183160017:web:beecca5df632c8156f93f0',
    messagingSenderId: '595183160017',
    projectId: 'dsm-project-7087e',
    authDomain: 'dsm-project-7087e.firebaseapp.com',
    storageBucket: 'dsm-project-7087e.firebasestorage.app',
    measurementId: 'G-HKXRK8MNVE',
  );

}